### PR TITLE
Build static binaries by default, various other improvements

### PR DESCRIPTION
**Pull request by tklauser**
Make sure statically linked binaries are built for the release. Also drop the dependency on github.com/cilium/cilium to avoid pulling in lots of transitive dependencies.

See individual commit messages for details.

### CODE REVIEW

**Comment by brb** [comment]
@tklauser If I run `make release` locally, I'm getting the following build error:
```
...
Compiled /pwru/kprobepwruwithoutoutputskb_bpfeb.o
Wrote /pwru/kprobepwruwithoutoutputskb_bpfeb.go
Building release binary for linux/arm64...
Generating for arm64
fork/exec /tmp/go-build4112468209/b001/exe/bpf2go: exec format error
main_arm64.go:5: running "go": exit status 1
```
Is it expected?

**Comment by tklauser** [comment]
> @tklauser If I run `make release` locally, I'm getting the following build error:
> 
> ```
> ...
> Compiled /pwru/kprobepwruwithoutoutputskb_bpfeb.o
> Wrote /pwru/kprobepwruwithoutoutputskb_bpfeb.go
> Building release binary for linux/arm64...
> Generating for arm64
> fork/exec /tmp/go-build4112468209/b001/exe/bpf2go: exec format error
> main_arm64.go:5: running "go": exit status 1
> ```
> 
> Is it expected?

That's certainly not expected. I cannot reproduce this here but I wonder whether that is because I have QEMU user emulation enabled (I think). Could you past the full log of running `make release`?

**Comment by tklauser** [comment]
> That's certainly not expected. I cannot reproduce this here but I wonder whether that is because I have QEMU user emulation enabled (I think). Could you past the full log of running `make release`?

Ah no, can't be because of QEMU user emulation because the build should run inside the docker container.

**Comment by brb** [comment]
Full log:
```
$~/sandbox/gopath/src/github.com/cilium/pwru [03:57:54]
> make release
docker run \
        --env "RELEASE_UID=1000" \
        --env "RELEASE_GID=1000" \
        --rm \
        --workdir /pwru \
        --volume `pwd`:/pwru docker.io/library/golang:1.17.6-alpine3.15 \
        sh -c "apk add --no-cache make git clang && make local-release VERSION=v0.0.3-1-gd672722"
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/15) Installing libffi (3.4.2-r1)
(2/15) Installing libgcc (10.3.1_git20211027-r0)
(3/15) Installing libstdc++ (10.3.1_git20211027-r0)
(4/15) Installing xz-libs (5.2.5-r0)
(5/15) Installing libxml2 (2.9.12-r2)
(6/15) Installing llvm12-libs (12.0.1-r0)
(7/15) Installing clang-libs (12.0.1-r1)
(8/15) Installing clang (12.0.1-r1)
(9/15) Installing brotli-libs (1.0.9-r5)
(10/15) Installing nghttp2-libs (1.46.0-r0)
(11/15) Installing libcurl (7.80.0-r0)
(12/15) Installing expat (2.4.3-r0)
(13/15) Installing pcre2 (10.39-r0)
(14/15) Installing git (2.34.1-r0)
(15/15) Installing make (4.3-r0)
Executing busybox-1.34.1-r3.trigger
OK: 244 MiB in 30 packages
rm -f pwru
rm -f kprobepwru_bpf*
rm -f kprobepwruwithoutoutputskb_bpf*
rm -rf ./release
OS=linux; \
ARCHS='amd64 arm64'; \
for ARCH in $ARCHS; do \
        echo Building release binary for $OS/$ARCH...; \
        test -d release/$OS/$ARCH|| mkdir -p release/$OS/$ARCH; \
        env GOOS=$OS GOARCH=$ARCH go generate; \
        env GOOS=$OS GOARCH=$ARCH go build  -ldflags "-w -s -X 'github.com/cilium/pwru/internal/pwru.Version=v0.0.3-1-gd672722'" -o release/$OS/$ARCH/pwru ; \
        tar -czf release/pwru-$OS-$ARCH.tar.gz -C release/$OS/$ARCH pwru; \
        (cd release && sha256sum pwru-$OS-$ARCH.tar.gz > pwru-$OS-$ARCH.tar.gz.sha256sum); \
        rm -r release/$OS; \
done; \
if [ $(id -u) -eq 0 -a -n "$RELEASE_UID" -a -n "$RELEASE_GID" ]; then \
        chown -R "$RELEASE_UID:$RELEASE_GID" release; \
fi
Building release binary for linux/amd64...
Generating for amd64
/pwru/bpf/kprobe_pwru.c:351:21: warning: taking address of packed member 'print_skb_id' of class or structure 'event_t' may result in an unaligned pointer value [-Waddress-of-packed-member]
                set_skb_btf(skb, &event->print_skb_id);
                                  ^~~~~~~~~~~~~~~~~~~
1 warning generated.
Compiled /pwru/kprobepwru_bpfel.o
Wrote /pwru/kprobepwru_bpfel.go
/pwru/bpf/kprobe_pwru.c:351:21: warning: taking address of packed member 'print_skb_id' of class or structure 'event_t' may result in an unaligned pointer value [-Waddress-of-packed-member]
                set_skb_btf(skb, &event->print_skb_id);
                                  ^~~~~~~~~~~~~~~~~~~
1 warning generated.
Compiled /pwru/kprobepwru_bpfeb.o
Wrote /pwru/kprobepwru_bpfeb.go
/pwru/bpf/kprobe_pwru.c:351:21: warning: taking address of packed member 'print_skb_id' of class or structure 'event_t' may result in an unaligned pointer value [-Waddress-of-packed-member]
                set_skb_btf(skb, &event->print_skb_id);
                                  ^~~~~~~~~~~~~~~~~~~
1 warning generated.
Compiled /pwru/kprobepwruwithoutoutputskb_bpfel.o
Wrote /pwru/kprobepwruwithoutoutputskb_bpfel.go
/pwru/bpf/kprobe_pwru.c:351:21: warning: taking address of packed member 'print_skb_id' of class or structure 'event_t' may result in an unaligned pointer value [-Waddress-of-packed-member]
                set_skb_btf(skb, &event->print_skb_id);
                                  ^~~~~~~~~~~~~~~~~~~
1 warning generated.
Compiled /pwru/kprobepwruwithoutoutputskb_bpfeb.o
Wrote /pwru/kprobepwruwithoutoutputskb_bpfeb.go
Building release binary for linux/arm64...
Generating for arm64
fork/exec /tmp/go-build382696965/b001/exe/bpf2go: exec format error
main_arm64.go:5: running "go": exit status 1
```

**Comment by brb** [comment]
Tried it on different machine - hitting the same error.

**Comment by tklauser** [comment]
Issue with running `make release` should be fixed in https://github.com/cilium/pwru/pull/49/commits/6044379d048346900a219e824cb15596d55b48d2

**Review by brb — APPROVED** [review]
:rocket:

**Pull request merged**
